import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }), {
    ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
  }, { waitUntil() {}, passThroughOnException() {} });
}

test("renders the finished portfolio home", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /EduTool/);
  assert.match(html, /Slotronome/);
  assert.match(html, /Welcome to my heart\. Have fun\./);
  assert.match(html, /Welcome to my heart\.<\/span><span[^>]*>Have fun\./);
  assert.match(html, /— Tian Xing/);
  const introGuard = html.indexOf("html.phone-intro-pending{background:#020305!important}");
  const phoneMarkup = html.indexOf('class="phone-product"');
  assert.ok(introGuard >= 0 && phoneMarkup > introGuard, "the pre-paint dark-field guard must arrive before the phone markup");
  assert.match(html, /html\.phone-intro-pending body\{visibility:hidden!important\}/);
  assert.match(html, /dataset\.phoneIntro = 'pending'/);
  assert.doesNotMatch(html, /tian-phone-intro-played/);
  assert.doesNotMatch(html, /Portfolio · Edition 01|Selected work|2024—2026|Tian Xing delivers|Designed &amp; built by Tian Xing|New York/i);
  assert.doesNotMatch(html, /Choose an icon to open a project|Nine things I care about|makes things|systems thinking and play/i);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/);
});

test("renders a project detail route", async () => {
  const response = await render("/projects/surge-method/");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Push\. Recover\. Come back stronger\./);
  assert.match(html, /View on the App Store/);
  assert.match(html, /main-hi\.png/);
});

test("embeds playable projects and full-resolution screenshots", async () => {
  const response = await render("/projects/bebop-puzzle/");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Play Bebop Puzzle here/);
  assert.match(html, /https:\/\/beboppuzzle\.com/);
  assert.match(html, /bebop-live\.png/);
  assert.match(html, /FULL RESOLUTION/);
});

test("keeps the iPhone interactive and time-aware", async () => {
  const source = await readFile(new URL("../app/components/PhoneExperience.tsx", import.meta.url), "utf8");
  const phone3dSource = await readFile(new URL("../app/components/Phone3DIntro.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const photoManifest = await readFile(new URL("../app/photoManifest.ts", import.meta.url), "utf8");
  const projectSource = await readFile(new URL("../app/projects.ts", import.meta.url), "utf8");
  const soundSource = await readFile(new URL("../app/sound.ts", import.meta.url), "utf8");
  assert.match(source, /toLocaleTimeString/);
  assert.match(source, /Go to iPhone Home screen/);
  assert.match(source, /matchMedia\("\(max-width: 560px\)"\)/);
  assert.match(source, /className="mobile-home-nav"/);
  assert.match(source, /label: "Fun"/);
  assert.match(source, /media\/about\/tian-xing-iphone4\.jpg/);
  assert.match(source, /navigator\.mediaDevices\.getUserMedia/);
  assert.match(source, /xingpicture@gmail\.com/);
  assert.match(source, /xing_tian_lifeitself/);
  assert.match(source, /Happiness comes from\\nsolving problems\.\\n\\n— Mark Manson/);
  assert.doesNotMatch(source, /\| "maps"|MapsApp/);
  assert.equal((photoManifest.match(/media\/photos\/all\//g) ?? []).length, 28);
  const photoPaths = [...photoManifest.matchAll(/"src": "(\/media\/photos\/all\/[^"]+)"/g)].map((match) => match[1]);
  assert.equal(new Set(photoPaths).size, photoPaths.length);
  assert.match(source, /Delete Photo/);
  assert.match(source, /onDeleteCapture/);
  assert.match(source, /PHOTO_HIDDEN_KEY/);
  assert.match(source, /setPointerCapture/);
  assert.match(source, /Delete Photo\?/);
  assert.match(source, /Recently Deleted/);
  assert.match(source, /role="alertdialog"/);
  assert.match(source, /permanently removed from this device/);
  assert.match(source, /scrollIntoView/);
  assert.match(source, /event\.key === "ArrowLeft"/);
  assert.match(source, /script\.google\.com\/macros\/s\/AKfycby/);
  assert.match(source, /MESSAGE_DRAFT_KEY/);
  assert.match(source, /MESSAGE_THREAD_KEY/);
  assert.match(source, /Message sent\./);
  assert.match(source, /Try Again/);
  assert.match(source, /enterKeyHint="send"/);
  assert.doesNotMatch(source, /Delivered ✓/);
  assert.match(source, /Photo Booth effects/);
  assert.match(source, /photo-viewer/);
  assert.match(source, /WeatherScene/);
  assert.match(source, /geocoding-api\.open-meteo\.com/);
  assert.match(source, /7-DAY FORECAST/);
  assert.match(source, /Switch to degrees/);
  assert.match(source, /WEATHER_CACHE_KEY/);
  assert.match(source, /precipitation_probability/);
  assert.match(source, /SUNRISE & SUNSET/);
  assert.match(source, /Dragon egg timer/);
  assert.match(source, /endTimeRef/);
  assert.match(source, /Reset timer/);
  assert.match(source, /role="slider"/);
  assert.match(source, /has hatched/);
  // Every cue is synthesized in one shared engine, so the phone has a single
  // voice and a single switch that silences it.
  assert.match(soundSource, /AudioContext/);
  assert.match(soundSource, /export function playSound/);
  assert.match(soundSource, /export function toggleRinger/);
  assert.match(soundSource, /tian-iphone-ringer/);
  assert.doesNotMatch(soundSource, /\.mp3|\.wav|\.m4a|\.aac|decodeAudioData/);
  assert.doesNotMatch(source, /new AudioContextClass|createOscillator/);
  assert.match(source, /playSound\("shutter"\)/);
  assert.match(source, /playSound\("send"\)/);
  assert.match(source, /playSound\("chime"\)/);
  assert.match(source, /function playKeyboardTick/);
  assert.match(source, /status-ringer/);
  assert.match(source, /ringer-hud/);
  assert.match(styles, /\.ringer-switch\.is-silent/);
  assert.match(styles, /@keyframes ringer-hud-card/);
  assert.match(source, /watchDragon/);
  assert.match(source, /dragonCombo/);
  assert.match(styles, /dragon-bond-chip/);
  assert.match(source, /createDragonCard/);
  assert.match(source, /hydrateDragonCard/);
  assert.match(source, /dragonRarityOdds/);
  assert.match(source, /chooseDragonKind/);
  assert.match(source, /RITUAL POWER/);
  assert.match(source, /MYTHIC/);
  assert.match(styles, /dragon-rarity-forecast/);
  assert.match(source, /--ritual-charge/);
  assert.match(styles, /overflow:clip/);
  assert.match(source, /DRAGON_TRAITS/);
  assert.match(source, /visitDragon/);
  assert.match(source, /data-dragon-id/);
  assert.match(source, /BOND \+\$\{bondGain\}/);
  assert.match(styles, /dragon-pattern-speckle/);
  assert.match(styles, /is-active-dragon/);
  assert.match(styles, /fun-portal-open/);
  assert.match(source, /fun-icon-shell/);
  assert.match(source, /function FunShelf/);
  assert.match(source, /projects\.slice\(0, 9\)\.map/);
  assert.match(source, /--launch-scale-x/);
  assert.match(source, /--launch-width/);
  assert.match(source, /data-app-id=\{app\.id\}/);
  assert.match(source, /shouldReturnToFunIcon/);
  assert.match(source, /className="phone-product"/);
  assert.match(source, /className="status-time"/);
  assert.match(source, /className="phone-back"/);
  assert.match(source, /<Phone3DIntro productRef=\{phoneProductRef\} \/>/);
  assert.match(source, /ref=\{phoneProductRef\}/);
  assert.match(phone3dSource, /zero-depth rounded glass face/i);
  assert.match(phone3dSource, /function withoutInwardFaces/);
  assert.match(phone3dSource, /const bandGeometry = withoutInwardFaces\(rawBandGeometry\)/);
  assert.match(phone3dSource, /pointsInward/);
  assert.match(phone3dSource, /function machinedButtonGeometry/);
  assert.match(phone3dSource, /new THREE\.LatheGeometry/);
  assert.match(phone3dSource, /bevelSegments: 10/);
  assert.doesNotMatch(phone3dSource, /displayGasket|gasketGeometry|linerGeometry/);
  // The rotating model and the resting phone now share the live DOM screen.
  // This removes the old canvas-texture crossfade (and its one-frame wallpaper/icon jump).
  assert.doesNotMatch(phone3dSource, /createIntroScreenTexture/);
  assert.doesNotMatch(phone3dSource, /introDisplayMaterial/);
  assert.doesNotMatch(phone3dSource, /domHandoff/);
  assert.match(phone3dSource, /product\.style\.visibility = "visible"/);
  assert.match(phone3dSource, /DOM front has backface-visibility:hidden/);
  assert.match(phone3dSource, /new THREE\.ShapeGeometry\(faceShape/);
  assert.match(phone3dSource, /faceShape\.holes/);
  assert.match(phone3dSource, /SCREEN_COMPOSITE_Z = GLASS_Z \+ 0\.004/);
  assert.match(phone3dSource, /new THREE\.MeshBasicMaterial\(\{ color: 0x010203 \}\)/);
  assert.match(phone3dSource, /const backSubstrate = new THREE\.MeshBasicMaterial/);
  assert.match(phone3dSource, /const backCoverGlass = new THREE\.MeshPhysicalMaterial/);
  assert.match(phone3dSource, /ior: 1\.52/);
  assert.match(phone3dSource, /FUJI_CASE_ART/);
  assert.match(phone3dSource, /const frostedCaseMaterial = new THREE\.MeshPhysicalMaterial/);
  assert.match(phone3dSource, /function traceRoundedRectAt/);
  assert.match(phone3dSource, /const cameraCutout = traceRoundedRectAt/);
  assert.match(phone3dSource, /const rearCameraBezel = new THREE\.MeshPhysicalMaterial/);
  assert.match(phone3dSource, /new THREE\.TorusGeometry\(0\.126, 0\.018/);
  assert.doesNotMatch(phone3dSource, /cameraCutout\.absellipse/);
  assert.match(phone3dSource, /let caseTextureReady = !showFujiCase/);
  assert.match(phone3dSource, /if \(!modelActive \|\| introStarted \|\| !caseTextureReady\) return/);
  assert.match(phone3dSource, /startedAt = performance\.now\(\)/);
  assert.match(phone3dSource, /\/media\/cases\/red-fuji-case\.jpg/);
  assert.doesNotMatch(phone3dSource, /file\.nbfox\.com/);
  assert.match(phone3dSource, /product\.style\.transform/);
  assert.match(phone3dSource, /introRequestedForDocument/);
  assert.match(phone3dSource, /delete document\.documentElement\.dataset\.phoneIntro/);
  assert.doesNotMatch(phone3dSource, /sessionStorage/);
  assert.doesNotMatch(phone3dSource, /host\.style\.visibility = "hidden"/);
  assert.match(source, /folder-portal-body/);
  assert.match(source, /--launch-body-scale-y/);
  assert.match(styles, /fun-body-shared-close/);
  assert.match(styles, /fun-chrome-stay-close/);
  assert.match(styles, /\.fun-icon-shell\{[\s\S]*?inset:auto;[\s\S]*?left:var\(--launch-x\);[\s\S]*?top:var\(--launch-y\)/);
  assert.doesNotMatch(source, /phone-edge edge-left/);
  assert.doesNotMatch(source, /phone-spine/);
  assert.doesNotMatch(styles, /@keyframes phone-product-flip/);
  assert.match(styles, /phone-3d-ready:not\(\.phone-3d-complete\) \.phone-product/);
  assert.match(styles, /phone-product>\.phone:has\(\.screen\.phone-mode-folder\)/);
  assert.match(styles, /water-drops\.png/);
  assert.match(styles, /transform:scale\(1\.035,1\.012\)/);
  assert.match(styles, /phone-3d-ready \.phone-product \.status-bar[\s\S]*padding-inline:13px/);
  assert.match(styles, /\.status-time\s*\{[^}]*left:50%[^}]*translate\(-50%,-50%\)/);
  assert.doesNotMatch(styles, /@keyframes phone-dom-handoff/);
  assert.doesNotMatch(styles, /\.edge-left/);
  assert.doesNotMatch(styles, /@keyframes phone-spine-reveal/);
  assert.doesNotMatch(source, /className="back-mark"/);
  assert.match(styles, /animation:fun-portal-open 920ms/);
  assert.match(styles, /animation:fun-icon-arrive 490ms calc\(300ms/);
  assert.match(styles, /@keyframes fun-content-dolly-open/);
  assert.match(styles, /@keyframes fun-page-home-close/);
  assert.match(styles, /transform:translate3d\(var\(--launch-x\),var\(--launch-y\),0\) scale\(var\(--launch-scale-x\),var\(--launch-scale-y\)\)/);
  assert.match(styles, /@keyframes fun-content-close \{ 0%,28%\{opacity:1/);
  assert.match(styles, /@keyframes fun-portal-close/);
  assert.match(styles, /sys-folder \.fun-shelf\.is-compact/);
  assert.doesNotMatch(source, />TX</);
  assert.match(styles, /phone-app-layer\.is-opening\.is-from-icon/);
  assert.match(styles, /backface-visibility:hidden/);
  assert.match(styles, /device-stage\.is-immersive\{translate:none/);
  assert.match(styles, /prefers-reduced-motion/);
  assert.match(source, /Draw on this note/);
  assert.match(source, /NOTES_STORAGE_KEY/);
  assert.match(source, /Search notes/);
  assert.match(source, /Undo drawing/);
  assert.match(source, /Redo drawing/);
  assert.match(source, /Toggle eraser/);
  assert.match(source, /stored on this device/);
  assert.doesNotMatch(source, /type="range"/);
  assert.match(source, /radio\.garden/);
  assert.match(source, /THE WILD WEB/);
  assert.match(source, /SAFARI_STAMPS_KEY/);
  assert.match(source, /startExpedition/);
  assert.match(source, /safari-passport/);
  assert.match(source, /safari-starfield/);
  assert.match(source, /safari-compass-glass/);
  assert.doesNotMatch(source, /safari-basecamp/);
  assert.match(styles, /safari-compass/);
  assert.match(styles, /safari-signal-pulse/);
  assert.equal((source.match(/media\/ios4\/icons\//g) ?? []).length, 2);
  assert.doesNotMatch(source, /Photo Portfolio/);
  for (const icon of ["messages", "calendar", "photos", "camera", "weather", "clock", "notes", "phone", "mail", "safari", "music"]) {
    await access(new URL(`../public/media/ios4/icons/${icon}.png`, import.meta.url));
  }
  const safariIcon = await readFile(new URL("../public/media/ios4/icons/safari.png", import.meta.url));
  assert.equal(safariIcon.readUInt32BE(16), 512);
  assert.equal(safariIcon.readUInt32BE(20), 512);
  assert.match(projectSource, /slug: "edutool"[\s\S]{0,180}year: "2026"/);
  assert.match(projectSource, /slug: "start-where-you-are"[\s\S]{0,180}year: "2025"/);
  assert.match(projectSource, /slug: "texas-jack"[\s\S]{0,180}year: "2024"/);
  assert.match(projectSource, /slug: "slotronome"[\s\S]{0,180}year: "2025"/);
  assert.match(source, /open\.spotify\.com\/embed\/playlist\/6hYj1RoYJ85hj8c1kaDFJ2/);
  assert.doesNotMatch(source, /appstore|youtube:|id: "about"/i);
});
